services:
    skuola_seo.twig_pagination_meta.extension:
        class: "%skuola_seo.twig_pagination_meta.extension.class%"
        arguments: [ "@router", "@service_container"]
        calls:
            - [setRequestStack, [ "@request_stack" ]]
        tags:
            - { name: twig.extension }
