services:
    skuola_seo.twig_pagination_meta.extension:
        class: %skuola_seo.twig_pagination_meta.extension.class%
        arguments: [ "@router" ]
        tags:
            - { name: twig.extension }