services:
    skuola_seo.twig_pagination_meta.extension:
        class: %skuola_seo.twig_pagination_meta.extension.class%
        arguments: [ "@request_stack", "@router", "%domain%" ]
        tags:
            - { name: twig.extension }